### PR TITLE
mobian installer: Fix desktop file

### PR DESCRIPTION
**Pull request by sc0w**
It fixes some wrong folders, now is working with this change.

### CODE REVIEW

**Comment by Flaburgan** [comment]
So is the script up-to-date with your repo now?

**Review by Flaburgan — CHANGES_REQUESTED** [review]
I trust you on the content of the script as I don't have a mobian install to test, but can you please rename the file to remove the version number?

**Comment by sc0w** [comment]
@Flaburgan Thanks for your quick answer

done!

**Comment by Flaburgan** [comment]
Merged, thank you! :cookie:

**Comment by nuehm-arno** [comment]
I cannot confirm the changes with v0.9.8 on Mobian.

**Pull request merged**
