### PR TITLE
Add "add contact" and "edit contact" to chat menu

### PR DESCRIPTION
**Pull request by nanu-c**
This adds the possibility to add a unknown number directly to the contacts or edit the name from the chat. It also updates some dependencies of axolotl web and  i have my linter fighting with my prettier...

### CODE REVIEW

**Review by nuehm-arno — COMMENTED** [review]
You deleted `(state, ` in the `delChat` function (line 394) as well. I assume, it is not needed for `this.state.socket.isConnected`?

**Review by nuehm-arno — APPROVED** [review]
I think, it is good to use `const` instead of `var`, if a declaration occurs only once.

Edit: I pressed the wrong button and approved all changes, sorry, that was to fast. I only meant the "use const instead of var in store" commit.

**Review by nuehm-arno — COMMENTED** [review]
Regarding the "more type safety" commit --> Approved.

**Review by nuehm-arno — COMMENTED** [review]
Regarding the "remove debug logging" commit --> Approved

**Review by nuehm-arno — COMMENTED** [review]
Regarding the 'Add "add contact" and "edit contact" to chat menu' commit and the changes in _Header.vue_:

I think, I understood the two different `@click` actions. The `addContactModal` gets the current number from `currentChat.Tel` - so no function is needed.
While for editing the contact, you need the `openEditContactModal` function to be called after the click for getting the contact id, isn't it?

**Comment by nanu-c** [comment]
> Regarding the 'Add "add contact" and "edit contact" to chat menu' commit and the changes in _Header.vue_:
> 
> I think, I understood the two different `@click` actions. The `addContactModal` gets the current number from `currentChat.Tel` - so no function is needed.
> While for editing the contact, you need the `openEditContactModal` function to be called after the click for getting the contact id, isn't it?

That's right, what we have is the tel and the chatId because historically grown, we have the tel as unique identifier, so we need to search for it in the contacts in order to modify the correct contact.

Thanks for the review

**Pull request merged**
