### PR TITLE
translate dates

### PR DESCRIPTION
**Pull request by nanu-c**
they are now all in English but can be in any language

### CODE REVIEW

**Comment by olof-nord** [comment]
Thanks to @Danfro, right? (I cant seem to tag him/her though)

**Comment by Danfro** [comment]
Thanks @olof-nord  Me is him. :-) I didn't do nothing. Was just throwing code bits at @nanu-c . :grinning:

**Comment by Flaburgan** [comment]
The date at the bottom of the messages still is "now", is that because it is not translated in french in the po file?

**Comment by nanu-c** [comment]
translating the now needs another Idea 
https://github.com/nanu-c/axolotl/blob/3eda8a16bc1c1f4a762fa5f38382f91e0865e218/axolotl-web/src/pages/ChatList.vue#L94-L98

**Comment by Flaburgan** [comment]
Indeed, it works, but kinda break the design. The date is now on two lines in french:

image

As I plan to refactor the layout anyway, I propose merge this, but in the 0.9. Are you fine with that?

**Comment by nanu-c** [comment]
I am fine with that, in the 0.9.0 goes the magic :)

**Comment by Flaburgan** [comment]
Merged! I'll start my refactor of the layout "soon".

**Pull request merged**
