### PR TITLE
Mobian installer link added

### PR DESCRIPTION
**Pull request by nuehm-arno**
A simple link to the installer repo should be easier to maintain.

### CODE REVIEW

**Comment by nuehm-arno** [comment]
Ok, I see, the revert request isn't fully merged. My bad. So please just add the github link to the Mobian section. That would be nice.
Thank you very much!

**Comment by Flaburgan** [comment]
@nuehm-arno why not putting this script in that repo directly?

**Comment by nuehm-arno** [comment]
Isn't it more complicated for you guys, to add a new version, everytime something of that quite complicated building process changes and the script has to be adjusted?
If not, feel free to add v1.4 to your repo - I would be honoured!

**Comment by Flaburgan** [comment]
Well, it isn't more complicated for us to simply merge you if you submit the needed changes, and it will surely be more discoverable by users here so I would vote for that.

**Review by Flaburgan — CHANGES_REQUESTED** [review]
Please update the script directly in that repo in the scripts folder and then link it in the README

**Comment by Flaburgan** [comment]
Superseded by https://github.com/nanu-c/axolotl/pull/388

**Comment by nuehm-arno** [comment]
Ok, I will update the script here.

**Pull request closed without merging**
