### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nuehm-arno**
Additional files needed for Debian arm64 packaging

### CODE REVIEW

**Comment by nuehm-arno** [comment]
This is the first commit to create the "deb" folder in the repo. More files will be added afterwards.

**Comment by sc0w** [comment]
this is putting the cart before the horse.

https://github.com/nuehm-arno/axolotl-mobian-package

why your repo doesn't have debian folder if it is needed to make the package?

why we must to think it is safe?

**Comment by nuehm-arno** [comment]
If you have looked into my axolotl-debian-packaging repo, you would have seen, that there is indeed need for this folder and the files inside.

**Comment by sc0w** [comment]
https://www.debian.org/doc/manuals/maint-guide/dreq.en.html

the folder must be named `debian` , not `deb`

and with `copyright` file, not `license`

**Comment by sc0w** [comment]
> If you have looked into my axolotl-debian-packaging repo, you would have seen, that there is indeed need for this folder and the files inside.

how did you make the `.deb` file without `debian` folder?

**Comment by nuehm-arno** [comment]
Please, have a look into the Makefile or this [PR](https://github.com/nanu-c/axolotl/pull/507). You'll find everything there and believe me, I have done my research to build a Debian package accordingly - as seen in the Lintian log.

**Comment by olof-nord** [comment]
Is there any chance the LICENSE file in the root of the repo can be used instead of this?
I see the danger of having two, and creating "two truths".

**Comment by nuehm-arno** [comment]
> Is there any chance the LICENSE file in the root of the repo can be used instead of this?
> I see the danger of having two, and creating "two truths".

Sadly not. Debian is not accepting a full license in packaging. I tried that and Lintian was not amused.

**Comment by nuehm-arno** [comment]
If you all agree to this folder, I will add other files like a desktop file or logo png, which are specificly customized to comply with Debian packaging rules - which is annoying, I know, but necessary.
These other files from [here](https://github.com/nuehm-arno/axolotl-debian-packaging/tree/main/deb) will come in a separate PR afterwards.

**Pull request merged**
