### PR TITLE
main english language: Fix some words

### PR DESCRIPTION
**Pull request by sc0w**
https://en.wikipedia.org/wiki/QR_code

Please update `pot` / `po` files if merge

Thanks

### CODE REVIEW

**Comment by olof-nord** [comment]
all .po files `msgId`s have been updated.

The translations.json file as well.

**Comment by olof-nord** [comment]
Looks good to me. Anything missing here, or can this be merged @nanu-c?

**Comment by nanu-c** [comment]
now i produced a merge conflict and i am not a git wizard to solve it. so please solve it and then we can merge it.

**Comment by sc0w** [comment]
I fixed the conflicts

It just need to update again `pot` / `po` files

**Comment by olof-nord** [comment]
> all .po files `msgId`s have been updated.
> 
> The translations.json file as well.

Did it all again.

**Comment by nanu-c** [comment]
Thank you sc0w!

**Pull request merged**
