### PR TITLE
Axolotl Electron: Update to latest v18.x

### PR DESCRIPTION
**Pull request by olof-nord**
Upgrade to the latest Electron version for the bundler and the standalone Electron execution.

### CODE REVIEW

**Comment by olof-nord** [comment]
> 

The beauty of astilectron is that it is just a thin wrapper around the github release page, and as such support any release which has a github release. I see v18.0.0 and v18.0.1 - not sure which one to pick.

On their [own documentation](https://releases.electronjs.org/), they list both 17 and 18 (also 16 for the record) as supported.

https://github.com/electron/electron/releases/

**Comment by olof-nord** [comment]
> 

The beauty of astilectron is that it is just a thin wrapper around the github release page, and as such support any release which has a github release. I see v18.0.0 and v18.0.1 - not sure which one to pick.

On their [own documentation](https://releases.electronjs.org/), they list both 17 and 18 (also 16 for the record) as supported.

https://github.com/electron/electron/releases/

**Comment by nuehm-arno** [comment]
Then let's bump it to 18.0.1 and I will test the deb file from the PR.

**Comment by nuehm-arno** [comment]
I just tested Electron v18.0.1 without Ozone/Wayland on Mobian and Axolotl works. But there is still this nasty input bug where ü and V are not working. I wonder when this will be fixed - either on the Mobian or Electron side.
Electron with Ozone/Wayland crashes as usual...

**Pull request merged**
