### PR TITLE
Update AddContactModal.vue

### PR DESCRIPTION
**Pull request by nuehm-arno**
Adding this info will prevent user from incorrect number input.

### CODE REVIEW

**Comment by nuehm-arno** [comment]
Another solution could be to expand the placeholder in line 36...

**Comment by olof-nord** [comment]
Another idea would be to add a phone number validator.

I had a look around for vue3 libraries, and this one seems to be one option.

https://www.npmjs.com/package/vue-phone-number-input

```
import VuePhoneNumberInput from 'vue-phone-number-input';
import 'vue-phone-number-input/dist/vue-phone-number-input.css';

Vue.component('vue-phone-number-input', VuePhoneNumberInput);

<VuePhoneNumberInput v-model="yourValue" />
```

**Comment by nanu-c** [comment]
Actually we should do the check the number at the go side and improve the functions here: https://github.com/nanu-c/axolotl/blob/main/app/contact/contact.go I see room for improvements.

**Comment by nuehm-arno** [comment]
Closing in favour of contact.go modifications.

**Pull request closed without merging**
