### PR TITLE
Fix #415 and Vue unit tests with chai+mocha

### LINKED ISSUE #415: [BUG] Message Content between characters "<" and ">" is missing in message bubble
### Description

If a message contains the character "<", followed by a non white-space character, those characters and all following text up to an eventual ">" character is missing in the message bubble. 
Example:
The message `<hi how are > you` is rendered ` you`
The message `< hi how are > you` however, is rendered correctly.

Ascii-Art like `<3` and all following text is hidden that way. No affection through Axolotl.

The message is rendered correctly as last message of the chat in the chat list.

Fun fact: github has this bug, too. My first example was rendered "<hi how are > you", before I wrapped it in a code block.
But at least github is able to render "<3" correctly. Github likes affection. :)

### Steps to Reproduce

1. Write or receive a message containing "<" followed by any non white-space character.

**Expected behavior:**

The message bubble contains the full message

**Actual behavior:**

The message bubble only contains the part of the message up to the character "<" and, if present, the part after the character ">".
The message is shown completely in the chat list, as long as it is the last message of that chat. 

#### Versions

Found in 0.9.8 

#### Device <-- this section should maybe named "Device and OS"? 

Volla Phone running Ubuntu Touch

#### Link to Debug Log

Nothing related in the logs

### PR DESCRIPTION
**Pull request by Blackoverflow**
Fix #415 

But I also wanted to write unit tests for my fix, so I introduced chai+mocha.

That wasn't quite as easy as I hoped for, but I manged it. :)

### CODE REVIEW

**Comment by Blackoverflow** [comment]
Where is the .deepsource.toml ?
`'mocha'` needs to be added to the `environment` array.

**Comment by Blackoverflow** [comment]
I didn't understand how to sort the imports in order to pass deepsource. They are alphabetically...

**Comment by Blackoverflow** [comment]
I request that "squash and merge" will be used in order to remove all those import sorting commits.^^

**Comment by nanu-c** [comment]
Now that i merged the other branch, the changelog has to be rebased ;)

**Comment by Blackoverflow** [comment]
Changelog proposal:
* Fix Messages with special characters (e.g. "<") not displayed correctly (blackoverflow)
* Introduced Chai+Mocha for Vue unit tests (blackoverflow)

**Review by nanu-c — APPROVED** [review]

**Comment by nanu-c** [comment]
Thank you! I love this really a lot! I accidently didn't squash, but ...

**Comment by Blackoverflow** [comment]
Thank you. :)

Well, its a bit spam for the commit history.^^

**Pull request merged**
