### PR TITLE
Add missing protobuf dependency abseil to Flatpak manifest

### PR DESCRIPTION
**Pull request by darkdragon-001**
61360aae7ff4b4f699aeab20067ff3d672a44f08 added protobuf dependency but missed the transitive abseil one. Adding it here to fix the Flatpak build.

813c2fefbe4972d6b2639c7ab04e4343fbf536a0 removed the source links in `Cargo.lock`, re-adding them via `cargo update --workspace`.

### CODE REVIEW

**Comment by nanu-c** [comment]
Thanks for your work here! It's very appreciated.
One short note: 
When the flatpak build is in the build stage, when it fails it will block the other packaging steps. My knowledge in flatpak is rather limited and I am relaying on other persons to fix it. Thats why i put it in package step. Also we want to ensure, that it builds at all before we do the packaging.

image

vs
image

**Comment by darkdragon-001** [comment]
> Thanks for your work here! It's very appreciated. One short note: When the flatpak build is in the build stage, when it fails it will block the other packaging steps. My knowledge in flatpak is rather limited and I am relaying on other persons to fix it. Thats why i put it in package step. Also we want to ensure, that it builds at all before we do the packaging.

Is is very annoying to wait 10m+ before Flatpak build even starts when trying to fix it.

Can we just move everything in a single workflow file and use `needs:` keyword to mark dependencies? This way the whole workflow would be faster as also package jobs would start as soon as the build artifacts are available. What do you think?

**Comment by darkdragon-001** [comment]
@nanu-c I moved the workflow changes to #1169 and only kept the necessary Flatpak fixes here. Could you please take a look?

**Review by nanu-c — APPROVED** [review]
Really really cool! Thanks

**Pull request merged**
