### PR TITLE
French translation updated

### PR DESCRIPTION
**Pull request by Anne017**

### CODE REVIEW

**Comment by nanu-c** [comment]
The problem here is, translation is broken, and vuejs isn't using po files

**Comment by nanu-c** [comment]
can you redo it on master?

**Comment by Anne017** [comment]
I am not sure to understand, am I not already targeting nanu-c:master?
Or is it another "master" you are talking about?

I see the fr.po file has been recently updated in your repository, should I close this pull request and propose another update in a new one?

**Comment by Flaburgan** [comment]
Hi @Anne017 :)
Yes some updates to the french translation have been pull, you need to rebase your work or start over. Are you familiar with git and merging conflict or do you need help?

**Comment by Anne017** [comment]
I not familiar with merging conflict, it should not be very difficult but I prefer to start over to ensure the full translation is clean

**Pull request closed without merging**
