### PR TITLE
Flatpak CI builds: Address crayfish build errors

### PR DESCRIPTION
**Pull request by olof-nord**
Attempt to address the flatpak cmake build errors by manually install the missing protobuf dependency.

### CODE REVIEW

**Comment by nanu-c** [comment]
Regarding this issue https://github.com/tokio-rs/prost/issues/709#event-7233952173 maybe adding `protoc` is enough.

**Comment by olof-nord** [comment]
After trying a few different methods without any success, I have opened a ticket here as to find out what Fedora dependencies are required for protobuf: https://github.com/tokio-rs/prost/issues/712

**Comment by nanu-c** [comment]
I have included the `build.rs` adoptions in crayfish in this mr https://github.com/nanu-c/axolotl/pull/886

**Comment by olof-nord** [comment]
Closing this PR, the fix is included with #886.

**Pull request closed without merging**
