### PR TITLE
[axolotl-web] Review Message component linter messages

### PR DESCRIPTION
**Pull request by olof-nord**
Follow eslint configuration for the Message component.

Converting all `var`s to `const`s.
Switching to type-safe equality checks.

**Question 1**
There are two null checks done against the `message.Attachment` prop/variable.

Unless this variable explicitly is set to the string "null", I believe the check to verify if the variable is null should be written with null written as a constant and not as a string as to receive the expected results.

This is relevant for line 104 and 129.

old: `message.Attachment !== 'null'` (with single quotation marks)
new? `message.Attachment !== null`

**Question 2**

Reading up on .contains, this helper class is used on strings to search for a contained word. 
`"axolotl says hello".includes("axolotl"); -> true.`

I do not understand how or if there could be a case of the Attachment variable containing the string "null", also in this case I am wondering if perhaps it is of interest if the string on the whole is null.

This is relevant for line 17 and 140.

old: `message.Attachment.includes('null')` (with string search)
new? `message.Attachment === null` or `message.Attachment.length === 0`.

In the quest to find out this small, but still important questions, could you list some example values for `message.Attachment`?
Interesting here would be both "happy path" of what normally should happen, and some error scenarios.

**Question 3**
This is purely out of curiosity. On line 257, the return value is multiplied with `179`. I cannot for my life figure out why this value is used here, is this something you could share some insights to? As to avoid "magic numbers" perhaps this value could be assigned a constant, and then used? Just providing a name for the value might give some info regarding its purpose.

### CODE REVIEW

**Comment by nanu-c** [comment]
Okey i try to answer your questions.

Regarding Question 1
grafik
If the attachment is null, there is really the string `null` in there. It's like that for historical reasons and I think I never touched that part. Maybe this answers also question 2 partly. We can improve the situation, but maybe after the groupsv2 change. Maybe we should open an issue for it?

Question 3:
The `timerPercentage` is used to draw the circle in the self destructing messages. It consist of 3 div that are transformed to represent the percentage. Like `transform: rotate(' + timerPercentage(message) + 'deg)` 
The `179` represents a full circle so we can add a constant for that explanation.

**Comment by olof-nord** [comment]
I see! Really appreciate you taking the time to answer. I added a const for the self destructing message percentage calculation.

I could surely open an issue for the "null" string value for a null attachment, but I dont see the need at this very moment. It could possibly be documented somewhere, but better to focus on other things I think.

**Comment by nanu-c** [comment]
Thanks for all your work!

**Comment by nanu-c** [comment]
Thanks for all your work!

**Pull request merged**
