### PR TITLE
Add a message in the settings to explain about notifications

### PR DESCRIPTION
**Pull request by Flaburgan**

### CODE REVIEW

**Comment by Danfro** [comment]
Trying to help improving this further, I would like to leave some suggestions:

1. The app is names ["UT Tweak Tool"](https://gitlab.com/myii/ut-tweak-tool/-/blob/master/click/manifest.json.in#L3), the note should use this name (UT abbreviated, not fully spelled).
2. The corresponding English string is labelled ["Prevent app suspension"](https://gitlab.com/myii/ut-tweak-tool/-/blob/master/src/app/qml/applicationsTab/ApplicationPageOverviewTab.qml#L115), not "avoid being interrupted"
3. "to be warned" -> "to be notified" because it is a notification for new messages, not a warning
4. "Keep it open" -> "Keep the app open" might be clearer?
5. The area for the label is limited in size. Translated texts might not fit there without the need for scrolling [is that implemented?]. From our chat I remember we had ideas for several notes *1. So maybe a dedicated new page "Usage and information" might be better long term?
6. maybe add a line break before "In Ubuntu Touch ,,," because this gives OS specific intstuctions

*1 Note ideas:
- about Axolotl on desktop is considered a second device, not a replacement for Signal desktop
- note on unencrypted messages in the filesystem of UT, suggestion to use an in-app-password

**Comment by Flaburgan** [comment]
Thanks for the feedback, the wording is way better, I will change that next week I am in vacation currently.

**Comment by Flaburgan** [comment]
1, 2, 3, 4 and 6 have been addressed ;)
About 5, yes, there is scrolling in place. I don't want to create a new page at the moment, I will add the other information during the registration process. In this PR, it's more like a tutorial so I feel like it should be accessible and the settings is the first place where you go when something looks... not set ;)

**Review by nanu-c — APPROVED** [review]
Looks good to me. We can merge it

**Pull request merged**
