### PR TITLE
Mobian installer added

### PR DESCRIPTION
**Pull request by nuehm-arno**
Hello there,

here is the pull request for the Mobian installer.

I added some lines in README.md and docs/INSTALL.md.

Feel free to change the lines!

Cheers

### CODE REVIEW

**Comment by nanu-c** [comment]
Thanks a lot!

**Comment by nuehm-arno** [comment]
You're welcome!

And since I created a github project for the installer, it might be better to just add a link to the repo to save maintenance time, don't you think?

The repo is

https://github.com/nuehm-arno/axolotl-mobian-installer

And feel free to drop the merge or change lines yourself.

**Comment by sc0w** [comment]
how to update in mobian if trere is new version?

it needs one more script or it can be done easily?

and how to uninstall? one more script will be helpfull?

Thanks!

**Comment by nuehm-arno** [comment]
@sc0w 
You can do an update with v1.2 of the script.
Unistallation is a future-me task.

**Pull request merged**
