### PR TITLE
French translation updated

### PR DESCRIPTION
**Pull request by Anne017**

### CODE REVIEW

**Comment by Flaburgan** [comment]
Hello! @RedXXIII already started a PR on french translations there: https://github.com/nanu-c/axolotl/pull/354 can you please check together to see which work should be integrated? Thank you :cookie:

**Comment by RedXXIII** [comment]
Hello! I still need some time to finish my review. When do you need to
do the integration? 

Le 09/02/2021 23:54, Fla a écrit :

> Hello! @RedXXIII [1] already started a PR on french translations there: #354 [2] can you please check together to see which work should be integrated? Thank you 🍪 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/RedXXIII
[2] https://github.com/nanu-c/axolotl/pull/354
[3] https://github.com/nanu-c/axolotl/pull/363#issuecomment-776298958
[4]

**Comment by nanu-c** [comment]
Translations are merged always, when they are ready, and then they are in the next release, so no time frame.

**Comment by RedXXIII** [comment]
thanks great. Actually I took some time this morning and I have sent my
PR. But maybe Fla will want to have a look at it before integrate it. 

Le 10/02/2021 09:59, Aaron a écrit :

> Translations are merged always, when they are ready, and then they are in the next release, so no time frame. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/nanu-c/axolotl/pull/363#issuecomment-776550496
[2]

**Comment by nanu-c** [comment]
@Anne017  and @RedXXIII  we have 2 french merge request, both with a merge conflict. and if I resolve one of these branches, the other one will have one conflict more.

So I would like to ask, if someone of you can open a new merge request and include the changes from these 2 merge requests?

**Comment by RedXXIII** [comment]
Hello, 

I'm not very familiar with github... Anne017 would you like to do it?
I'm available if you have questions about my modifications. 

Le 04/05/2021 21:49, Aaron a écrit :

> @Anne017 [1] and @RedXXIII [2] we have 2 french merge request, both with a merge conflict. and if I resolve one of these branches, the other one will have one conflict more. 
> 
> So I would like to ask, if someone of you can open a new merge request and include the changes from these 2 merge requests? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/Anne017
[2] https://github.com/RedXXIII
[3] https://github.com/nanu-c/axolotl/pull/363#issuecomment-832199956
[4]

**Pull request closed without merging**
