### PR TITLE
Improve editing and adding contacts within existing chats

### PR DESCRIPTION
**Pull request by nanu-c**
This time i try to avoid big pr's and i try to split the things in smaller pieces.

This fixes, that the contact list is deleted, when we hit the server rate limit.
It also uses the uuid instead of the phone number for editing and adding existing chats to the contact list.
VCF import is not yet tested and improved.

In order to work with axolotl-web i had to update the packages.

### CODE REVIEW

**Comment by nanu-c** [comment]
closes #710, #530, #176, #381

**Review by olof-nord — COMMENTED** [review]
Amazing stuff, really appreciate the PR description.

Only thing I could think about is for the frontend part, to perhaps start thinking about small private component-based util functions for checks where we use many different values.

Then it might be clearer what the intent is, and it would arguably make the code more easy to read.

Now:
```typescript
v-if="chat && chat.IsGroup && chat.GroupJoinStatus !== 0"
```

Idea:
```typescript
v-if="showAddContactButton()"
```

**Comment by nanu-c** [comment]
I like the idea and i will add it to my vuejs "skillset" for the next changes, so i don't introduce more complicated if clause nesting.

**Comment by nanu-c** [comment]
closes also #393

**Comment by nanu-c** [comment]
Thank you for the review!

**Pull request merged**
